In [1]:
import torch

In [2]:
#intro to tensor

In [3]:
#create a tensor

In [4]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#get as python int
scalar.item()

7

In [7]:
#vector
vector=torch.tensor([7,7])

In [8]:
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#matrix

In [12]:
matrix=torch.tensor([[7,8],[4,3]])

In [13]:
matrix

tensor([[7, 8],
        [4, 3]])

In [14]:
matrix.ndim

2

In [15]:
matrix[0]

tensor([7, 8])

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
#tensor
tensor=torch.tensor([[[1,2,3],
                     [3,6,9],
                     [2,4,5],
                     [4,5,6]],
                    [[1,221,23],
                     [32,2322,44],
                     [23,23,222],
                     [2,3,22]]])

In [18]:
tensor

tensor([[[   1,    2,    3],
         [   3,    6,    9],
         [   2,    4,    5],
         [   4,    5,    6]],

        [[   1,  221,   23],
         [  32, 2322,   44],
         [  23,   23,  222],
         [   2,    3,   22]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([2, 4, 3])

In [21]:
tensor[1]

tensor([[   1,  221,   23],
        [  32, 2322,   44],
        [  23,   23,  222],
        [   2,    3,   22]])

In [22]:
#random tensor


In [23]:
random_tensor=torch.rand(2,2,3,4)

In [24]:
random_tensor

tensor([[[[0.7460, 0.1380, 0.4306, 0.7364],
          [0.7910, 0.4441, 0.7886, 0.7517],
          [0.2867, 0.5210, 0.8567, 0.2525]],

         [[0.7218, 0.0659, 0.2691, 0.2589],
          [0.0263, 0.0877, 0.8960, 0.3650],
          [0.6293, 0.2099, 0.5924, 0.1264]]],


        [[[0.7363, 0.4275, 0.8864, 0.2374],
          [0.0859, 0.0636, 0.2867, 0.5545],
          [0.5147, 0.0348, 0.3591, 0.8066]],

         [[0.3730, 0.7728, 0.0252, 0.3860],
          [0.9130, 0.1087, 0.2291, 0.2671],
          [0.0076, 0.0551, 0.7483, 0.7672]]]])

In [25]:
random_image_size_tensor=torch.rand(size=(3,6,6))

In [26]:
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 6, 6]), 3)

In [27]:
random_image_size_tensor

tensor([[[0.5979, 0.8157, 0.4393, 0.4015, 0.6881, 0.3143],
         [0.9156, 0.5655, 0.1718, 0.8961, 0.9079, 0.2587],
         [0.9961, 0.6607, 0.3615, 0.3244, 0.7575, 0.4312],
         [0.2514, 0.0245, 0.3941, 0.1436, 0.0698, 0.6570],
         [0.5249, 0.3342, 0.9820, 0.0919, 0.3479, 0.5890],
         [0.3280, 0.5975, 0.7618, 0.3004, 0.7640, 0.7977]],

        [[0.6636, 0.8581, 0.4345, 0.6653, 0.5445, 0.5726],
         [0.9387, 0.9084, 0.0240, 0.3970, 0.4653, 0.3271],
         [0.9273, 0.6238, 0.4098, 0.3347, 0.1042, 0.7141],
         [0.4801, 0.5270, 0.3568, 0.5773, 0.7714, 0.9978],
         [0.3869, 0.7121, 0.5014, 0.7612, 0.5969, 0.0029],
         [0.2810, 0.6287, 0.5946, 0.6491, 0.4883, 0.4451]],

        [[0.1170, 0.5492, 0.6822, 0.1933, 0.6687, 0.6137],
         [0.3616, 0.2080, 0.7957, 0.7269, 0.5472, 0.4559],
         [0.8466, 0.3267, 0.6021, 0.7378, 0.3987, 0.3333],
         [0.5989, 0.8523, 0.0783, 0.8674, 0.2068, 0.3307],
         [0.8414, 0.0039, 0.3840, 0.3227, 0.0051, 0.

In [28]:
#zeros and ones

In [29]:
zeros=torch.zeros(size=(3,6,6))

In [30]:
zeros.shape

torch.Size([3, 6, 6])

In [31]:
zeros*random_image_size_tensor

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [32]:
zeros.dtype

torch.float32

In [33]:
#create a range of tensor

In [34]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
one_to_hundred=torch.arange(start=1,end=100,step=10)

In [36]:
one_to_hundred

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [37]:
one_to_hundred.shape

torch.Size([10])

In [38]:
ten_zeros=torch.zeros_like(one_to_hundred)

In [39]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
#tensor datatype

In [41]:
float_32=torch.tensor([2.0,2.3,2.32],dtype=torch.float32,device=None,requires_grad=False)

In [42]:
float_32

tensor([2.0000, 2.3000, 2.3200])

In [43]:
float_32.dtype

torch.float32

In [44]:
float_16=float_32.type(torch.float16)

In [45]:
float_16

tensor([2.0000, 2.3008, 2.3203], dtype=torch.float16)

In [46]:
float_16*float_32

tensor([4.0000, 5.2918, 5.3831])

In [47]:
#getting info from tensor

In [48]:
float_32.shape

torch.Size([3])

In [49]:
float_32.dtype

torch.float32

In [50]:
float_32.device

device(type='cpu')

In [51]:
#manipulating tensor (tensor operations)

- Addition
- substaction
- multiplicatiopn elementwise
- division
- matrix multiplication

In [52]:
#create tensor
tensor=torch.tensor([1])
tensor+10

tensor([11])

In [53]:
tensor2=torch.rand((2,1))

In [54]:
tensor2

tensor([[0.5930],
        [0.5550]])

In [55]:
tensor2+10

tensor([[10.5930],
        [10.5550]])

In [56]:
tensor

tensor([1])

In [57]:
tensor+tensor2

tensor([[1.5930],
        [1.5550]])

In [58]:
#matrix multipliaction

In [59]:
torch.matmul(tensor2,tensor2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1 and 2x1)

In [60]:
#dimension must match

In [61]:
#errors

In [62]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [1,6]])

In [63]:
tensor_B=torch.tensor([[7,10],
                      [8,11],
                      [9,12]])

In [64]:
#TRANSPOSE OF TENSOR
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [65]:
torch.mm(tensor_A,tensor_B.T)

tensor([[27, 30, 33],
        [61, 68, 75],
        [67, 74, 81]])

### Random number within a range

In [39]:
import logging

def my_logger(function):
    ''' logger module as a decorator'''
    logging.basicConfig(filename=
                       f"{function.__name__}.log",
                       level=logging.INFO,
                       format='%(asctime)s %(levelname)s %(message)s')
    def wrapper(*args,**kwargs):
        logging.info(f"{function.__name__} ran with {args} and {kwargs}")
        result=function(*args,**kwargs)
        return result
    return wrapper

@my_logger
def random_gen(lower,upper,shape):
    try:
        tensor=(upper-lower)*torch.rand(shape)+lower
        tensor=tensor.type(torch.int)
    except Exception as e:
        logging.warning(e)
    else:
        return tensor

In [40]:
random=random_gen(1,8,(3,6,6))

In [41]:
random

tensor([[[4, 5, 1, 1, 2, 3],
         [2, 7, 5, 7, 1, 4],
         [7, 6, 2, 3, 1, 5],
         [2, 1, 4, 5, 4, 4],
         [3, 3, 7, 4, 2, 5],
         [1, 1, 5, 1, 7, 3]],

        [[2, 3, 4, 5, 7, 2],
         [7, 6, 1, 5, 7, 7],
         [3, 3, 3, 6, 5, 1],
         [2, 7, 7, 4, 1, 7],
         [5, 5, 3, 5, 1, 1],
         [3, 5, 6, 1, 7, 1]],

        [[5, 7, 2, 4, 6, 4],
         [4, 7, 1, 4, 6, 7],
         [6, 4, 2, 3, 6, 1],
         [4, 5, 7, 1, 4, 4],
         [4, 7, 7, 4, 3, 4],
         [7, 6, 2, 4, 2, 4]]], dtype=torch.int32)

## finding the min max,mean,sum,etc() tensor aggregation

In [47]:
tensor=random_gen(1,10,shape=(5,5,3))

In [48]:
tensor

tensor([[[1, 8, 7],
         [5, 5, 2],
         [5, 2, 5],
         [1, 9, 7],
         [9, 7, 6]],

        [[8, 4, 7],
         [6, 7, 2],
         [4, 8, 9],
         [2, 6, 3],
         [4, 9, 3]],

        [[9, 2, 5],
         [2, 2, 8],
         [3, 8, 1],
         [5, 3, 1],
         [8, 3, 6]],

        [[9, 3, 3],
         [4, 7, 6],
         [6, 8, 8],
         [2, 5, 8],
         [8, 8, 2]],

        [[1, 7, 2],
         [4, 4, 4],
         [7, 3, 3],
         [1, 9, 8],
         [5, 8, 8]]], dtype=torch.int32)

In [58]:
tensor.sum(dim=1)

tensor([[21, 31, 27],
        [24, 34, 24],
        [27, 18, 21],
        [29, 31, 27],
        [18, 31, 25]])

In [72]:
torch.mean(tensor.type(torch.float32))

tensor(5.6667)

In [73]:
tensor.sum(dim=0)

tensor([[ 9, 17, 16, 17, 19],
        [15, 15, 17, 18, 21],
        [21, 14, 18, 21, 17],
        [22, 21, 18, 17,  7],
        [19, 20, 12, 15, 19]])

#indexing

In [74]:
tensor.argmin(dim=0)

tensor([[1, 0, 2, 2, 2],
        [0, 1, 0, 0, 2],
        [2, 0, 0, 1, 2],
        [2, 0, 0, 1, 0],
        [0, 1, 0, 2, 1]])

In [75]:
tensor

tensor([[[4, 4, 6, 6, 8],
         [2, 6, 4, 5, 8],
         [9, 1, 1, 9, 8],
         [8, 6, 4, 7, 2],
         [6, 7, 2, 6, 9]],

        [[1, 4, 8, 8, 6],
         [5, 4, 8, 6, 9],
         [9, 9, 9, 3, 5],
         [8, 7, 6, 1, 2],
         [6, 5, 8, 5, 5]],

        [[4, 9, 2, 3, 5],
         [8, 5, 5, 7, 4],
         [3, 4, 8, 9, 4],
         [6, 8, 8, 9, 3],
         [7, 8, 2, 4, 5]]], dtype=torch.int32)

In [76]:
tensor.argmax(dim=0)

tensor([[0, 2, 1, 1, 0],
        [2, 0, 1, 2, 1],
        [0, 1, 1, 0, 0],
        [0, 2, 2, 2, 2],
        [2, 2, 1, 0, 0]])

## Reshaping, viewing, stacking, squeezing and unsqueezing

In [77]:
 x=random_gen(1,100,(3,4,4))

In [78]:
x,x.shape

(tensor([[[84, 86, 95,  5],
          [80, 63, 36, 68],
          [12, 72, 28,  4],
          [87, 14, 45, 55]],
 
         [[25, 80, 63, 45],
          [17, 68, 74, 86],
          [33, 84, 18, 78],
          [ 8, 43, 13, 10]],
 
         [[30, 97, 50, 41],
          [77, 22,  8,  3],
          [19, 40, 56, 98],
          [44, 30, 33, 80]]], dtype=torch.int32),
 torch.Size([3, 4, 4]))

In [79]:
#reshape
x_re=x.reshape(2,2,3,4)

In [80]:
x_re

tensor([[[[84, 86, 95,  5],
          [80, 63, 36, 68],
          [12, 72, 28,  4]],

         [[87, 14, 45, 55],
          [25, 80, 63, 45],
          [17, 68, 74, 86]]],


        [[[33, 84, 18, 78],
          [ 8, 43, 13, 10],
          [30, 97, 50, 41]],

         [[77, 22,  8,  3],
          [19, 40, 56, 98],
          [44, 30, 33, 80]]]], dtype=torch.int32)

In [81]:
#change the view

In [82]:
z=x.view(2,24)

In [83]:
z

tensor([[84, 86, 95,  5, 80, 63, 36, 68, 12, 72, 28,  4, 87, 14, 45, 55, 25, 80,
         63, 45, 17, 68, 74, 86],
        [33, 84, 18, 78,  8, 43, 13, 10, 30, 97, 50, 41, 77, 22,  8,  3, 19, 40,
         56, 98, 44, 30, 33, 80]], dtype=torch.int32)

In [84]:
z[0][2]=2

In [85]:
z

tensor([[84, 86,  2,  5, 80, 63, 36, 68, 12, 72, 28,  4, 87, 14, 45, 55, 25, 80,
         63, 45, 17, 68, 74, 86],
        [33, 84, 18, 78,  8, 43, 13, 10, 30, 97, 50, 41, 77, 22,  8,  3, 19, 40,
         56, 98, 44, 30, 33, 80]], dtype=torch.int32)

In [86]:
x

tensor([[[84, 86,  2,  5],
         [80, 63, 36, 68],
         [12, 72, 28,  4],
         [87, 14, 45, 55]],

        [[25, 80, 63, 45],
         [17, 68, 74, 86],
         [33, 84, 18, 78],
         [ 8, 43, 13, 10]],

        [[30, 97, 50, 41],
         [77, 22,  8,  3],
         [19, 40, 56, 98],
         [44, 30, 33, 80]]], dtype=torch.int32)

In [87]:
#stack tensor 

In [88]:
x=random_gen(1,15,shape=(4,4))

In [89]:
x

tensor([[ 5,  7,  6,  4],
        [12, 11,  5,  5],
        [ 4,  5,  6,  1],
        [11,  3,  2, 10]], dtype=torch.int32)

In [90]:
y=random_gen(1,15,shape=(4,4))

In [91]:
y

tensor([[ 3,  2,  9,  5],
        [13,  8,  7,  7],
        [ 5, 13, 10,  4],
        [ 8, 11,  4,  9]], dtype=torch.int32)

In [92]:
torch.stack((x,y),dim=1)

tensor([[[ 5,  7,  6,  4],
         [ 3,  2,  9,  5]],

        [[12, 11,  5,  5],
         [13,  8,  7,  7]],

        [[ 4,  5,  6,  1],
         [ 5, 13, 10,  4]],

        [[11,  3,  2, 10],
         [ 8, 11,  4,  9]]], dtype=torch.int32)

In [93]:
torch.stack((x,y),dim=1)[1][0][2]

tensor(5, dtype=torch.int32)

## sqeuzee


In [94]:
x=random_gen(1,44,(2,))

In [95]:
x,x.shape

(tensor([ 8, 12], dtype=torch.int32), torch.Size([2]))

In [96]:
x.unsqueeze(dim=0),x.unsqueeze(dim=0).shape

(tensor([[ 8, 12]], dtype=torch.int32), torch.Size([1, 2]))

In [97]:
x.squeeze(dim=0) 
#no reduction because x doesn't have the 1 dimension 

tensor([ 8, 12], dtype=torch.int32)

In [98]:
#2D
x=random_gen(1,44,(2,2))

In [99]:
x,x.shape

(tensor([[ 2, 12],
         [26, 22]], dtype=torch.int32),
 torch.Size([2, 2]))

In [100]:
x.unsqueeze(dim=0),x.unsqueeze(dim=0).shape

(tensor([[[ 2, 12],
          [26, 22]]], dtype=torch.int32),
 torch.Size([1, 2, 2]))

In [101]:
x.unsqueeze(dim=1),x.unsqueeze(dim=1).shape

(tensor([[[ 2, 12]],
 
         [[26, 22]]], dtype=torch.int32),
 torch.Size([2, 1, 2]))

In [102]:
x.unsqueeze(dim=2),x.unsqueeze(dim=2).shape

(tensor([[[ 2],
          [12]],
 
         [[26],
          [22]]], dtype=torch.int32),
 torch.Size([2, 2, 1]))

In [103]:
input = torch.randn(3,1,2,1,4)
input

tensor([[[[[ 1.2257,  0.6307,  0.4909,  1.1297]],

          [[-0.9871,  0.7669,  0.2389, -1.0696]]]],



        [[[[ 1.8798, -1.5875, -2.4449, -0.5858]],

          [[ 0.9322,  1.1685, -0.5414, -1.3715]]]],



        [[[[-0.0126,  0.3186, -0.9851, -1.2151]],

          [[-1.3402,  2.6585, -1.3173, -2.1521]]]]])

In [109]:
output = torch.squeeze(input,dim=1)

In [110]:
output,output.shape

(tensor([[[[ 1.2257,  0.6307,  0.4909,  1.1297]],
 
          [[-0.9871,  0.7669,  0.2389, -1.0696]]],
 
 
         [[[ 1.8798, -1.5875, -2.4449, -0.5858]],
 
          [[ 0.9322,  1.1685, -0.5414, -1.3715]]],
 
 
         [[[-0.0126,  0.3186, -0.9851, -1.2151]],
 
          [[-1.3402,  2.6585, -1.3173, -2.1521]]]]),
 torch.Size([3, 2, 1, 4]))

In [111]:
x=torch.tensor([[1,2],[3,4]])

In [112]:
x

tensor([[1, 2],
        [3, 4]])

In [113]:
x.squeeze()

tensor([[1, 2],
        [3, 4]])

In [114]:
a=x.unsqueeze(dim=0)

In [115]:
a[0][0]

tensor([1, 2])

In [116]:
a.shape

torch.Size([1, 2, 2])

In [117]:
b=x.unsqueeze(dim=1)

In [118]:
b

tensor([[[1, 2]],

        [[3, 4]]])

In [119]:
b.shape

torch.Size([2, 1, 2])

In [120]:
c=x.unsqueeze(dim=2)

In [121]:
c.shape

torch.Size([2, 2, 1])

In [122]:
x.shape

torch.Size([2, 2])

In [123]:
c

tensor([[[1],
         [2]],

        [[3],
         [4]]])

In [124]:
c[0][1][0]

tensor(2)

In [125]:
a[0][1][0]

tensor(3)

### one look for the 3D array

In [126]:
D=random_gen(1,10,shape=(3,6,6))

In [127]:
D

tensor([[[9, 1, 1, 3, 4, 2],
         [1, 1, 8, 6, 5, 1],
         [6, 3, 8, 6, 4, 7],
         [3, 8, 7, 2, 9, 4],
         [8, 8, 4, 8, 7, 6],
         [8, 7, 4, 1, 9, 1]],

        [[2, 9, 2, 8, 6, 4],
         [2, 6, 4, 1, 2, 9],
         [1, 8, 6, 5, 7, 9],
         [8, 1, 2, 8, 2, 5],
         [1, 8, 4, 6, 2, 1],
         [6, 2, 9, 1, 7, 3]],

        [[3, 4, 3, 3, 3, 2],
         [4, 8, 1, 9, 7, 3],
         [5, 7, 1, 3, 1, 2],
         [7, 4, 9, 1, 7, 7],
         [9, 3, 1, 9, 7, 2],
         [8, 4, 3, 6, 1, 6]]], dtype=torch.int32)

In [128]:
# squeeze dim=0 #nochange

In [129]:
D.squeeze(dim=2),D.squeeze(dim=2).shape

(tensor([[[9, 1, 1, 3, 4, 2],
          [1, 1, 8, 6, 5, 1],
          [6, 3, 8, 6, 4, 7],
          [3, 8, 7, 2, 9, 4],
          [8, 8, 4, 8, 7, 6],
          [8, 7, 4, 1, 9, 1]],
 
         [[2, 9, 2, 8, 6, 4],
          [2, 6, 4, 1, 2, 9],
          [1, 8, 6, 5, 7, 9],
          [8, 1, 2, 8, 2, 5],
          [1, 8, 4, 6, 2, 1],
          [6, 2, 9, 1, 7, 3]],
 
         [[3, 4, 3, 3, 3, 2],
          [4, 8, 1, 9, 7, 3],
          [5, 7, 1, 3, 1, 2],
          [7, 4, 9, 1, 7, 7],
          [9, 3, 1, 9, 7, 2],
          [8, 4, 3, 6, 1, 6]]], dtype=torch.int32),
 torch.Size([3, 6, 6]))

In [130]:
#unsqueeze dim=0

In [131]:
a=D.unsqueeze(dim=0)
a,D.unsqueeze(dim=0).shape

(tensor([[[[9, 1, 1, 3, 4, 2],
           [1, 1, 8, 6, 5, 1],
           [6, 3, 8, 6, 4, 7],
           [3, 8, 7, 2, 9, 4],
           [8, 8, 4, 8, 7, 6],
           [8, 7, 4, 1, 9, 1]],
 
          [[2, 9, 2, 8, 6, 4],
           [2, 6, 4, 1, 2, 9],
           [1, 8, 6, 5, 7, 9],
           [8, 1, 2, 8, 2, 5],
           [1, 8, 4, 6, 2, 1],
           [6, 2, 9, 1, 7, 3]],
 
          [[3, 4, 3, 3, 3, 2],
           [4, 8, 1, 9, 7, 3],
           [5, 7, 1, 3, 1, 2],
           [7, 4, 9, 1, 7, 7],
           [9, 3, 1, 9, 7, 2],
           [8, 4, 3, 6, 1, 6]]]], dtype=torch.int32),
 torch.Size([1, 3, 6, 6]))

In [132]:
#unsqueeze dim=1
b=D.unsqueeze(dim=1)
b,D.unsqueeze(dim=1).shape

(tensor([[[[9, 1, 1, 3, 4, 2],
           [1, 1, 8, 6, 5, 1],
           [6, 3, 8, 6, 4, 7],
           [3, 8, 7, 2, 9, 4],
           [8, 8, 4, 8, 7, 6],
           [8, 7, 4, 1, 9, 1]]],
 
 
         [[[2, 9, 2, 8, 6, 4],
           [2, 6, 4, 1, 2, 9],
           [1, 8, 6, 5, 7, 9],
           [8, 1, 2, 8, 2, 5],
           [1, 8, 4, 6, 2, 1],
           [6, 2, 9, 1, 7, 3]]],
 
 
         [[[3, 4, 3, 3, 3, 2],
           [4, 8, 1, 9, 7, 3],
           [5, 7, 1, 3, 1, 2],
           [7, 4, 9, 1, 7, 7],
           [9, 3, 1, 9, 7, 2],
           [8, 4, 3, 6, 1, 6]]]], dtype=torch.int32),
 torch.Size([3, 1, 6, 6]))

In [133]:
b[1][0][5][2]

tensor(9, dtype=torch.int32)

In [134]:
#unsqueeze dim=2
c=D.unsqueeze(dim=2)
c,D.unsqueeze(dim=2).shape

(tensor([[[[9, 1, 1, 3, 4, 2]],
 
          [[1, 1, 8, 6, 5, 1]],
 
          [[6, 3, 8, 6, 4, 7]],
 
          [[3, 8, 7, 2, 9, 4]],
 
          [[8, 8, 4, 8, 7, 6]],
 
          [[8, 7, 4, 1, 9, 1]]],
 
 
         [[[2, 9, 2, 8, 6, 4]],
 
          [[2, 6, 4, 1, 2, 9]],
 
          [[1, 8, 6, 5, 7, 9]],
 
          [[8, 1, 2, 8, 2, 5]],
 
          [[1, 8, 4, 6, 2, 1]],
 
          [[6, 2, 9, 1, 7, 3]]],
 
 
         [[[3, 4, 3, 3, 3, 2]],
 
          [[4, 8, 1, 9, 7, 3]],
 
          [[5, 7, 1, 3, 1, 2]],
 
          [[7, 4, 9, 1, 7, 7]],
 
          [[9, 3, 1, 9, 7, 2]],
 
          [[8, 4, 3, 6, 1, 6]]]], dtype=torch.int32),
 torch.Size([3, 6, 1, 6]))

## torch.permute

In [135]:
x_image=random_gen(1,44,shape=(6,6,3)) #(height, width, channel)

In [136]:
#permute to rearrange the axis (or dim) order

In [137]:
x_permuted=x_image.permute((2,1,0))

In [138]:
x_permuted

tensor([[[16, 42,  5,  5, 28, 35],
         [ 7, 42, 19, 43, 36, 23],
         [ 9, 32, 39, 38, 16, 26],
         [21,  8, 22, 29, 25, 40],
         [28, 37, 30, 40, 25, 16],
         [26, 40, 17, 33, 17, 19]],

        [[ 1, 20, 28,  1, 27, 11],
         [10, 43, 23, 13,  8, 38],
         [ 7, 11, 21,  2, 14, 24],
         [ 9, 37, 42, 31, 38, 14],
         [43, 42, 25, 19,  9, 11],
         [31, 12, 42,  6, 27, 12]],

        [[18, 22, 12,  5, 20, 11],
         [14, 40, 12, 26, 24,  2],
         [19,  9, 10, 35, 21, 38],
         [29, 24, 12,  3, 38,  4],
         [24,  2, 14, 14,  5,  9],
         [31, 24, 37, 14, 40, 10]]], dtype=torch.int32)

In [139]:
#indexing with tensor

In [141]:
x_image.shape

torch.Size([6, 6, 3])

In [142]:
x_image

tensor([[[16,  1, 18],
         [ 7, 10, 14],
         [ 9,  7, 19],
         [21,  9, 29],
         [28, 43, 24],
         [26, 31, 31]],

        [[42, 20, 22],
         [42, 43, 40],
         [32, 11,  9],
         [ 8, 37, 24],
         [37, 42,  2],
         [40, 12, 24]],

        [[ 5, 28, 12],
         [19, 23, 12],
         [39, 21, 10],
         [22, 42, 12],
         [30, 25, 14],
         [17, 42, 37]],

        [[ 5,  1,  5],
         [43, 13, 26],
         [38,  2, 35],
         [29, 31,  3],
         [40, 19, 14],
         [33,  6, 14]],

        [[28, 27, 20],
         [36,  8, 24],
         [16, 14, 21],
         [25, 38, 38],
         [25,  9,  5],
         [17, 27, 40]],

        [[35, 11, 11],
         [23, 38,  2],
         [26, 24, 38],
         [40, 14,  4],
         [16, 11,  9],
         [19, 12, 10]]], dtype=torch.int32)

In [146]:
x_image[0][1][1]

tensor(10, dtype=torch.int32)

In [152]:
x_image[:,:,1]

tensor([[ 1, 10,  7,  9, 43, 31],
        [20, 43, 11, 37, 42, 12],
        [28, 23, 21, 42, 25, 42],
        [ 1, 13,  2, 31, 19,  6],
        [27,  8, 14, 38,  9, 27],
        [11, 38, 24, 14, 11, 12]], dtype=torch.int32)

In [153]:
x_image[:,1,1]

tensor([10, 43, 23, 13,  8, 38], dtype=torch.int32)

In [154]:
x=torch.tensor([[[1,2,3],
                [4,5,6],
                [7,8,9]]])

In [156]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [160]:
x[0][2][2]

tensor(9)

In [164]:
x[:,:,2]

tensor([[3, 6, 9]])

# pytorch and numpy

In [168]:
#convert numpy to pytorch tensor
# torch.from_numpy(ndarray)

#from pytorch tensor to numpy
# torch.Tensor.numpy()

In [169]:
#numpy to tensor
import torch
import numpy as np


In [174]:
array=np.arange(1,10)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [176]:
array.dtype,tensor.dtype

(dtype('int32'), torch.float32)

In [180]:
#from tensor to numpy
arr=tensor.numpy()

In [181]:
arr.dtype

dtype('float32')

# Reproducbility ( trying to take random out of random

In short how a neural network learns:
'start with random numbers -> tensor operation -> update random number to try and make them better representation of the data -> again -> again...'


To reduce the randomness in NN and pytorch is with ** random seed **

In [187]:
import torch
#create tensor
A=torch.rand(3,4)
B=torch.rand(3,4)
print(A,B)
print(A==B)

tensor([[0.2038, 0.1017, 0.5091, 0.0471],
        [0.9968, 0.8610, 0.4879, 0.9941],
        [0.1411, 0.2828, 0.7974, 0.9625]]) tensor([[0.3950, 0.2486, 0.6612, 0.7344],
        [0.1536, 0.3506, 0.4506, 0.6494],
        [0.2072, 0.9523, 0.0996, 0.6275]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [188]:
#use of random seed

import torch
#set the random seed
random_seed=42
torch.manual_seed(random_seed)

In [193]:
import torch
#create tensor
torch.manual_seed(random_seed)
C=torch.rand(3,4)
torch.manual_seed(random_seed) 
D=torch.rand(3,4)
print(C,D)
print(C==D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Accessing GPU

In [194]:
#check for GPU access for pytorch

In [195]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [197]:
torch.cuda.is_available()

False

## setup device agnostic code

In [201]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [202]:
device

'cpu'

In [203]:
#count number of devices
torch.cuda.device_count()

0

# running on GPU

In [205]:
#create a tensor #not on GPU
tensor=random_gen(1,100,(3,3))

In [206]:
print(tensor,tensor.device)

tensor([[44, 30, 83],
        [11, 27, 36],
        [20, 55,  1]], dtype=torch.int32) cpu


In [209]:
tensor.to(device)

tensor([[44, 30, 83],
        [11, 27, 36],
        [20, 55,  1]], dtype=torch.int32)

In [210]:
#move tensor to cpu

In [211]:
# if tensor is on GPU, can't transform to numpy

In [212]:
tensor.cpu()

tensor([[44, 30, 83],
        [11, 27, 36],
        [20, 55,  1]], dtype=torch.int32)

In [213]:
tensor.cpu().numpy()

array([[44, 30, 83],
       [11, 27, 36],
       [20, 55,  1]])

In [1]:
import torch

In [35]:
a=torch.rand((3,4,4))

In [34]:
a[0][0][0]+a[0][0][1]+a[0][0][2]

tensor(2.3993)

In [36]:
print(a)

tensor([[[0.1327, 0.7925, 0.2618, 0.0581],
         [0.1079, 0.1121, 0.2307, 0.4326],
         [0.8868, 0.1665, 0.2949, 0.3606],
         [0.6654, 0.3995, 0.0417, 0.5283]],

        [[0.6238, 0.6500, 0.0280, 0.4176],
         [0.4585, 0.0740, 0.1685, 0.3500],
         [0.4312, 0.8629, 0.2094, 0.5178],
         [0.2855, 0.5570, 0.2079, 0.6160]],

        [[0.3942, 0.4036, 0.3672, 0.5985],
         [0.7657, 0.4916, 0.3846, 0.9911],
         [0.1342, 0.1254, 0.0336, 0.7399],
         [0.8426, 0.1480, 0.9893, 0.5915]]])


In [37]:
b=torch.sum(a,2)

In [38]:
print(b)

tensor([[1.2450, 0.8834, 1.7087, 1.6349],
        [1.7194, 1.0511, 2.0212, 1.6664],
        [1.7636, 2.6330, 1.0330, 2.5713]])


In [33]:
b.shape

torch.Size([4, 4])

In [63]:
a=torch.rand(5)

In [64]:
a

tensor([0.8243, 0.9642, 0.2005, 0.7480, 0.6620])

In [66]:
torch.fft.fft(a)

tensor([ 3.3990+0.0000j,  0.5596+0.0344j, -0.1982-0.6983j, -0.1982+0.6983j,
         0.5596-0.0344j])